export const MOVIES_DATA = [
  {
    name: "CR90 corvette",
    model: "CR90 corvette",
    manufacturer: "Corellian Engineering Corporation",
    cost_in_credits: "3500000",
    length: "150",
    max_atmosphering_speed: "950",
    crew: "30-165",
    passengers: "600",
    cargo_capacity: "3000000",
    consumables: "1 year",
    hyperdrive_rating: "2.0",
    MGLT: "60",
    starship_class: "corvette",
    pilots: [],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/6/",
    ],
    created: "2014-12-10T14:20:33.369000Z",
    edited: "2014-12-20T21:23:49.867000Z",
    url: "https://swapi.dev/api/starships/2/",
    id: "43u84u3iu4",
  },
  {
    id: "fierewioeiow",
    name: "Star Destroyer",
    model: "Imperial I-class Star Destroyer",
    manufacturer: "Kuat Drive Yards",
    cost_in_credits: "150000000",
    length: "1,600",
    max_atmosphering_speed: "975",
    crew: "47,060",
    passengers: "n/a",
    cargo_capacity: "36000000",
    consumables: "2 years",
    hyperdrive_rating: "2.0",
    MGLT: "60",
    starship_class: "Star Destroyer",
    pilots: [],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
    ],
    created: "2014-12-10T15:08:19.848000Z",
    edited: "2014-12-20T21:23:49.870000Z",
    url: "https://swapi.dev/api/starships/3/",
  },
  {
    id: "cewijecwijew",
    name: "Sentinel-class landing craft",
    model: "Sentinel-class landing craft",
    manufacturer: "Sienar Fleet Systems, Cyngus Spaceworks",
    cost_in_credits: "240000",
    length: "38",
    max_atmosphering_speed: "1000",
    crew: "5",
    passengers: "75",
    cargo_capacity: "180000",
    consumables: "1 month",
    hyperdrive_rating: "1.0",
    MGLT: "70",
    starship_class: "landing craft",
    pilots: [],
    films: ["https://swapi.dev/api/films/1/"],
    created: "2014-12-10T15:48:00.586000Z",
    edited: "2014-12-20T21:23:49.873000Z",
    url: "https://swapi.dev/api/starships/5/",
  },
  {
    id: "ccwijriwceiwjeiow",
    name: "Death Star",
    model: "DS-1 Orbital Battle Station",
    manufacturer:
      "Imperial Department of Military Research, Sienar Fleet Systems",
    cost_in_credits: "1000000000000",
    length: "120000",
    max_atmosphering_speed: "n/a",
    crew: "342,953",
    passengers: "843,342",
    cargo_capacity: "1000000000000",
    consumables: "3 years",
    hyperdrive_rating: "4.0",
    MGLT: "10",
    starship_class: "Deep Space Mobile Battlestation",
    pilots: [],
    films: ["https://swapi.dev/api/films/1/"],
    created: "2014-12-10T16:36:50.509000Z",
    edited: "2014-12-20T21:26:24.783000Z",
    url: "https://swapi.dev/api/starships/9/",
  },
  {
    id: "scdhwejwcioeuihrwc",
    name: "Millennium Falcon",
    model: "YT-1300 light freighter",
    manufacturer: "Corellian Engineering Corporation",
    cost_in_credits: "100000",
    length: "34.37",
    max_atmosphering_speed: "1050",
    crew: "4",
    passengers: "6",
    cargo_capacity: "100000",
    consumables: "2 months",
    hyperdrive_rating: "0.5",
    MGLT: "75",
    starship_class: "Light freighter",
    pilots: [
      "https://swapi.dev/api/people/13/",
      "https://swapi.dev/api/people/14/",
      "https://swapi.dev/api/people/25/",
      "https://swapi.dev/api/people/31/",
    ],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
    ],
    created: "2014-12-10T16:59:45.094000Z",
    edited: "2014-12-20T21:23:49.880000Z",
    url: "https://swapi.dev/api/starships/10/",
  },
  {
    id: "eiojioej2iojec2io2jio2",
    name: "Y-wing",
    model: "BTL Y-wing",
    manufacturer: "Koensayr Manufacturing",
    cost_in_credits: "134999",
    length: "14",
    max_atmosphering_speed: "1000km",
    crew: "2",
    passengers: "0",
    cargo_capacity: "110",
    consumables: "1 week",
    hyperdrive_rating: "1.0",
    MGLT: "80",
    starship_class: "assault starfighter",
    pilots: [],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
    ],
    created: "2014-12-12T11:00:39.817000Z",
    edited: "2014-12-20T21:23:49.883000Z",
    url: "https://swapi.dev/api/starships/11/",
  },
  {
    id: "wcehwicewjicejwioew",
    name: "X-wing",
    model: "T-65 X-wing",
    manufacturer: "Incom Corporation",
    cost_in_credits: "149999",
    length: "12.5",
    max_atmosphering_speed: "1050",
    crew: "1",
    passengers: "0",
    cargo_capacity: "110",
    consumables: "1 week",
    hyperdrive_rating: "1.0",
    MGLT: "100",
    starship_class: "Starfighter",
    pilots: [
      "https://swapi.dev/api/people/1/",
      "https://swapi.dev/api/people/9/",
      "https://swapi.dev/api/people/18/",
      "https://swapi.dev/api/people/19/",
    ],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
    ],
    created: "2014-12-12T11:19:05.340000Z",
    edited: "2014-12-20T21:23:49.886000Z",
    url: "https://swapi.dev/api/starships/12/",
  },
  {
    id: "ecwiejwiejciwjecioj23",
    name: "TIE Advanced x1",
    model: "Twin Ion Engine Advanced x1",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "unknown",
    length: "9.2",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "0",
    cargo_capacity: "150",
    consumables: "5 days",
    hyperdrive_rating: "1.0",
    MGLT: "105",
    starship_class: "Starfighter",
    pilots: ["https://swapi.dev/api/people/4/"],
    films: ["https://swapi.dev/api/films/1/"],
    created: "2014-12-12T11:21:32.991000Z",
    edited: "2014-12-20T21:23:49.889000Z",
    url: "https://swapi.dev/api/starships/13/",
  },
  {
    id: "ewcioejwicjwijeicj",
    name: "Executor",
    model: "Executor-class star dreadnought",
    manufacturer: "Kuat Drive Yards, Fondor Shipyards",
    cost_in_credits: "1143350000",
    length: "19000",
    max_atmosphering_speed: "n/a",
    crew: "279,144",
    passengers: "38000",
    cargo_capacity: "250000000",
    consumables: "6 years",
    hyperdrive_rating: "2.0",
    MGLT: "40",
    starship_class: "Star dreadnought",
    pilots: [],
    films: ["https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/3/"],
    created: "2014-12-15T12:31:42.547000Z",
    edited: "2014-12-20T21:23:49.893000Z",
    url: "https://swapi.dev/api/starships/15/",
  },
  {
    id: "ecweowiopekwoer",
    name: "Rebel transport",
    model: "GR-75 medium transport",
    manufacturer: "Gallofree Yards, Inc.",
    cost_in_credits: "unknown",
    length: "90",
    max_atmosphering_speed: "650",
    crew: "6",
    passengers: "90",
    cargo_capacity: "19000000",
    consumables: "6 months",
    hyperdrive_rating: "4.0",
    MGLT: "20",
    starship_class: "Medium transport",
    pilots: [],
    films: ["https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/3/"],
    created: "2014-12-15T12:34:52.264000Z",
    edited: "2014-12-20T21:23:49.895000Z",
    url: "https://swapi.dev/api/starships/17/",
  },
];
export const products = [
  {
    id: 1000,
    firstName: "Sanjay",
    lastName: "Cooper",
    email: "GRydinsky@elit.io",
    phone: "(843)369-1114",
    address: {
      streetAddress: "4914 Eget Ave",
      city: "Salem",
      state: "VT",
      zip: "92290",
    },
    description:
      "aenean sed pharetra mi nullam dolor hendrerit sit at nunc ante amet nullam at amet vel tincidunt tempor sagittis quis suspendisse aenean aliquam sed mi eget orci pulvinar id risus orci elit",
  },
  {
    id: 263,
    firstName: "Gabriel",
    lastName: "Zeigler",
    email: "YRenbarger@sed.com",
    phone: "(627)995-6283",
    address: {
      streetAddress: "2837 Sed Dr",
      city: "Vienna",
      state: "WY",
      zip: "40827",
    },
    description:
      "elementum nec aenean eros scelerisque consectetur vitae tellus odio ac amet massa vel amet amet ac nec odio eget sit sed sapien magna adipiscing libero id sed at vitae etiam nec vel",
  },
  {
    id: 97,
    firstName: "Rosa",
    lastName: "Young",
    email: "SShaffer@amet.com",
    phone: "(600)879-4837",
    address: {
      streetAddress: "9306 Tortor Ave",
      city: "Philadelphia",
      state: "CA",
      zip: "41470",
    },
    description:
      "tortor odio id dolor sed suspendisse vestibulum libero suspendisse lorem et convallis tincidunt sed vitae magna aliquam vestibulum porta turpis porta odio eros risus molestie id dolor massa sagittis at pulvinar libero",
  },
  {
    id: 260,
    firstName: "Lilia",
    lastName: "Winder",
    email: "CChow@magna.org",
    phone: "(853)734-5470",
    address: {
      streetAddress: "4088 Tortor Ave",
      city: "Goodyear",
      state: "ME",
      zip: "65692",
    },
    description:
      "placerat aliquam pulvinar magna nunc dolor curabitur donec donec sapien consectetur suspendisse magna porta ipsum lacus massa magna orci magna mi eget aliquam aenean augue neque vitae dolor porta elit mattis in",
  },
  {
    id: 35,
    firstName: "David",
    lastName: "Carnevale",
    email: "BGow@egestas.com",
    phone: "(288)704-5391",
    address: {
      streetAddress: "7632 Libero Dr",
      city: "Evanston",
      state: "NV",
      zip: "80670",
    },
    description:
      "massa ante egestas sit ante augue etiam amet vel placerat sit vestibulum dolor aliquam elit magna vestibulum vitae elit nullam molestie dolor et vestibulum vitae sollicitudin mattis placerat nullam nec pharetra augue",
  },
  {
    id: 336,
    firstName: "Grace",
    lastName: "Rearick",
    email: "NLittle@vel.io",
    phone: "(691)842-6142",
    address: {
      streetAddress: "8327 Scelerisque Ct",
      city: "Selma",
      state: "NM",
      zip: "33333",
    },
    description:
      "vel aliquam sed rutrum odio vel et lectus vestibulum at pulvinar mattis scelerisque lacus massa etiam non ante mattis at nec risus nunc turpis in vestibulum molestie mattis et dui pulvinar dolor",
  },
  {
    id: 710,
    firstName: "Jessica",
    lastName: "Reddy",
    email: "DMuth@sollicitudin.org",
    phone: "(312)741-1094",
    address: {
      streetAddress: "3991 Nunc Rd",
      city: "Brodhead",
      state: "FL",
      zip: "36332",
    },
    description:
      "aenean magna placerat placerat nullam quis aliquam orci amet sit lacus hendrerit at libero pulvinar amet tortor aliquam nec dolor vitae massa tellus et fringilla massa pulvinar suspendisse donec fringilla curabitur consequat",
  },
  {
    id: 274,
    firstName: "Rali",
    lastName: "Giera",
    email: "ZDrolet@adipiscing.gov",
    phone: "(746)710-9607",
    address: {
      streetAddress: "908 Etiam Dr",
      city: "Coeur D'alene",
      state: "NC",
      zip: "44387",
    },
    description:
      "magna risus massa orci aenean tempor vestibulum lacus sollicitudin fringilla et ipsum fringilla sit tincidunt nullam placerat eros sollicitudin hendrerit elementum nullam nec ac scelerisque sed sit sollicitudin vitae amet odio tincidunt",
  },
  {
    id: 882,
    firstName: "Latasha",
    lastName: "Reckling",
    email: "STveter@pulvinar.org",
    phone: "(340)364-0242",
    address: {
      streetAddress: "3696 Augue Rd",
      city: "Salt Lake City",
      state: "TN",
      zip: "22729",
    },
    description:
      "mattis sollicitudin scelerisque scelerisque nec et hendrerit nullam vestibulum aenean adipiscing porttitor ante magna pulvinar ipsum tincidunt odio odio turpis donec tincidunt lectus vel consectetur lorem amet sed sollicitudin lorem ac sollicitudin",
  },
  {
    id: 633,
    firstName: "Tijana",
    lastName: "Garbe",
    email: "TAsfour@placerat.org",
    phone: "(303)914-7888",
    address: {
      streetAddress: "4641 Morbi Ln",
      city: "Manchester",
      state: "IA",
      zip: "28589",
    },
    description:
      "convallis sapien tortor lacus egestas lacus etiam molestie etiam donec magna sed ipsum adipiscing in mattis hendrerit magna quis vitae lacus amet curabitur amet ac dolor in elit sit scelerisque donec vitae",
  },
  {
    id: 831,
    firstName: "Janet",
    lastName: "Henke",
    email: "MCase@ipsum.io",
    phone: "(715)432-9523",
    address: {
      streetAddress: "1227 Aenean Ct",
      city: "Williamstown",
      state: "RI",
      zip: "59270",
    },
    description:
      "sit vitae morbi sed velit id rutrum tortor sit pretium sed hendrerit pharetra turpis egestas magna mi et rutrum tellus rutrum in dolor odio vel hendrerit nullam nullam vitae orci sagittis malesuada",
  },
  {
    id: 990,
    firstName: "Humayun",
    lastName: "Medina",
    email: "LPepin@sed.net",
    phone: "(631)962-4297",
    address: {
      streetAddress: "8249 Sapien St",
      city: "Panama City",
      state: "AR",
      zip: "24776",
    },
    description:
      "odio tincidunt convallis id sagittis tincidunt lacus quis magna tempor lacus massa vitae id porttitor pulvinar et malesuada ac magna libero sollicitudin hendrerit nec curabitur fringilla porttitor donec amet amet libero consequat",
  },
  {
    id: 912,
    firstName: "Kathy",
    lastName: "Gibson",
    email: "JMundie@quis.net",
    phone: "(286)851-3558",
    address: {
      streetAddress: "1585 Lectus Ave",
      city: "Minneola",
      state: "WY",
      zip: "64509",
    },
    description:
      "vestibulum vel tempor fringilla aenean adipiscing ipsum sollicitudin dui nunc tortor consectetur tincidunt ac et sit amet porttitor rutrum malesuada at orci turpis fringilla consequat molestie id orci sed risus lacus lectus",
  },
  {
    id: 186,
    firstName: "Vida",
    lastName: "Garcia",
    email: "GDenton@adipiscing.gov",
    phone: "(438)198-8382",
    address: {
      streetAddress: "7919 Mi Dr",
      city: "Kingsville",
      state: "IL",
      zip: "21159",
    },
    description:
      "tincidunt suspendisse facilisis at aliquam placerat amet mattis facilisis sit lorem vestibulum elementum sit sit at at aliquam odio ac massa consectetur egestas elit mattis lorem in nullam orci magna sed magna",
  },
  {
    id: 713,
    firstName: "Aylesa",
    lastName: "Mcwhorter",
    email: "LGiera@orci.net",
    phone: "(409)248-9401",
    address: {
      streetAddress: "9882 Sed Dr",
      city: "Underwood",
      state: "MA",
      zip: "47429",
    },
    description:
      "porttitor sit malesuada tempor pharetra tincidunt nunc neque aliquam eros vitae tortor scelerisque sit nullam nec at elit lacus consectetur magna sit tempor at convallis convallis dui eget lectus mattis massa turpis",
  },
  {
    id: 297,
    firstName: "Marlon",
    lastName: "Beverage",
    email: "EMorse@pretium.com",
    phone: "(249)028-2754",
    address: {
      streetAddress: "890 Eget Dr",
      city: "Hampton",
      state: "IL",
      zip: "19412",
    },
    description:
      "vitae augue sagittis elementum vestibulum elementum ipsum tortor convallis velit lacus sed elit turpis turpis in pulvinar dui scelerisque ac at non dolor risus sed lacus vestibulum in fringilla tincidunt porttitor risus",
  },
  {
    id: 821,
    firstName: "Magdalena",
    lastName: "Stokes",
    email: "LWelch@lorem.gov",
    phone: "(237)912-5271",
    address: {
      streetAddress: "9351 Pulvinar Ave",
      city: "Rosenberg",
      state: "IN",
      zip: "96937",
    },
    description:
      "dolor quis neque eget tortor dolor amet donec eget sollicitudin sollicitudin adipiscing eros pharetra magna lacus adipiscing mattis porta sapien aliquam malesuada facilisis malesuada consectetur et ipsum egestas pharetra neque libero aliquam",
  },
  {
    id: 672,
    firstName: "Camille",
    lastName: "Kirk",
    email: "MPeltonen@eros.com",
    phone: "(498)867-9240",
    address: {
      streetAddress: "2256 Odio Ave",
      city: "Moulton",
      state: "IN",
      zip: "17397",
    },
    description:
      "id et tortor tellus suspendisse aliquam nullam nec vitae orci vestibulum sit vel sed odio massa facilisis et lorem mattis et sit sit porttitor scelerisque eros orci elit egestas nunc vestibulum id",
  },
  {
    id: 730,
    firstName: "Arlesia",
    lastName: "Mcwethy",
    email: "MShay@sagittis.io",
    phone: "(766)760-2596",
    address: {
      streetAddress: "7071 Pulvinar Ave",
      city: "Kelso",
      state: "VA",
      zip: "68416",
    },
    description:
      "at ipsum tortor ac augue egestas adipiscing sed fringilla ac massa nunc at egestas at elit dolor curabitur amet tellus sollicitudin hendrerit eros et tortor amet in sollicitudin sapien pretium pretium lacus",
  },
  {
    id: 633,
    firstName: "Jezus",
    lastName: "Lafaye",
    email: "CLau@lacus.io",
    phone: "(187)990-6050",
    address: {
      streetAddress: "43 Pretium Rd",
      city: "Gaithersburg",
      state: "VA",
      zip: "55848",
    },
    description:
      "tortor suspendisse odio elit malesuada convallis nullam vestibulum vitae elit sollicitudin adipiscing vitae elit sit molestie tellus pulvinar porta sit nunc donec vestibulum lorem placerat nullam aliquam et tortor amet elit nunc",
  },
  {
    id: 664,
    firstName: "Ali",
    lastName: "Wright",
    email: "KFeger@facilisis.gov",
    phone: "(649)823-9353",
    address: {
      streetAddress: "7461 Egestas Rd",
      city: "Kingsland",
      state: "KY",
      zip: "51118",
    },
    description:
      "nec sagittis magna scelerisque molestie tincidunt augue orci consectetur vestibulum fringilla vestibulum at ante lacus neque dolor vitae consectetur porta pharetra magna dui mi magna et elementum sollicitudin ipsum velit porttitor sollicitudin",
  },
  {
    id: 339,
    firstName: "Douglass",
    lastName: "Dawn",
    email: "ASchemanski@pharetra.net",
    phone: "(319)239-6261",
    address: {
      streetAddress: "8699 Eros Ave",
      city: "Bradenton",
      state: "WA",
      zip: "11523",
    },
    description:
      "convallis odio sagittis sed aliquam lectus malesuada aliquam libero risus id ante facilisis vestibulum sed amet sit tincidunt pulvinar odio dui risus lacus placerat tortor consectetur odio nunc pretium etiam egestas ipsum",
  },
  {
    id: 847,
    firstName: "Janice",
    lastName: "Mathis",
    email: "CMcgrath@amet.ly",
    phone: "(619)426-9543",
    address: {
      streetAddress: "7449 Sed Ct",
      city: "Santa Monica",
      state: "IL",
      zip: "78044",
    },
    description:
      "sed lacus neque adipiscing dolor adipiscing sit donec velit aliquam vestibulum consequat suspendisse suspendisse non convallis aliquam donec in convallis sed orci sagittis risus lectus magna sit libero tortor non in facilisis",
  },
  {
    id: 206,
    firstName: "Ian",
    lastName: "Bunker",
    email: "JGuindin@lectus.ly",
    phone: "(887)613-4735",
    address: {
      streetAddress: "5228 Risus Ct",
      city: "Lewiston",
      state: "CA",
      zip: "13253",
    },
    description:
      "mattis vitae elit mi hendrerit ac placerat consectetur adipiscing turpis porta mi lacus tortor elit placerat id sit at ante consectetur elit tortor at tortor elementum rutrum dui risus scelerisque libero convallis",
  },
  {
    id: 822,
    firstName: "Earnest",
    lastName: "Leavitt",
    email: "MRaymond@consectetur.io",
    phone: "(956)567-9937",
    address: {
      streetAddress: "664 Tincidunt Dr",
      city: "Rawlins",
      state: "WY",
      zip: "23911",
    },
    description:
      "tempor ipsum vitae lacus nec vel pulvinar et orci convallis sollicitudin massa mattis sagittis massa id mi porta amet consequat amet mi curabitur sed risus nullam sollicitudin tincidunt vitae at morbi quis",
  },
  {
    id: 772,
    firstName: "Aydin",
    lastName: "Conn",
    email: "JDerucher@hendrerit.gov",
    phone: "(662)953-1969",
    address: {
      streetAddress: "560 Mattis St",
      city: "Kingwood",
      state: "OR",
      zip: "28939",
    },
    description:
      "vitae non molestie elementum morbi amet consectetur porta lacus sollicitudin pharetra aenean eget consequat sed egestas tortor id pulvinar eros vitae malesuada massa nec egestas etiam at eros aenean suspendisse magna magna",
  },
  {
    id: 246,
    firstName: "Krissy",
    lastName: "Stevenson",
    email: "RRannila@magna.org",
    phone: "(674)802-9348",
    address: {
      streetAddress: "2207 Mattis Ave",
      city: "Brighton",
      state: "AK",
      zip: "98889",
    },
    description:
      "rutrum sed massa sit tortor et ac nunc elementum consectetur lacus sollicitudin sed at at tincidunt facilisis hendrerit ac consequat ante massa pulvinar odio eget sit mattis sollicitudin non in tincidunt pulvinar",
  },
  {
    id: 385,
    firstName: "Hope",
    lastName: "Rizk",
    email: "HHolden@dui.gov",
    phone: "(397)631-0527",
    address: {
      streetAddress: "3500 Sollicitudin Dr",
      city: "Winfield",
      state: "KY",
      zip: "17235",
    },
    description:
      "facilisis id sollicitudin neque vitae vestibulum tempor sit dolor sit magna ante nec pretium et nunc amet vitae elementum lacus curabitur massa elementum eros nunc odio tortor pulvinar porta porta lorem sed",
  },
  {
    id: 501,
    firstName: "Nathan",
    lastName: "Case",
    email: "KDemeritt@morbi.com",
    phone: "(314)096-1245",
    address: {
      streetAddress: "404 Nunc Ct",
      city: "Lynchburg",
      state: "SC",
      zip: "48424",
    },
    description:
      "nec tincidunt egestas libero magna sapien amet sollicitudin ac ac sollicitudin velit scelerisque sapien augue sit sed sed sapien mi rutrum sollicitudin nullam sollicitudin neque turpis ante sit eros ante vitae eget",
  },
  {
    id: 468,
    firstName: "Domingo",
    lastName: "Heitert",
    email: "JMcmyne@nunc.net",
    phone: "(311)404-3316",
    address: {
      streetAddress: "8193 Vitae Ave",
      city: "Jackson Heights",
      state: "DE",
      zip: "42193",
    },
    description:
      "at sit porttitor risus egestas tempor sed donec donec sit velit augue magna ipsum sed donec odio sed sed facilisis odio in neque dolor dolor aenean pretium neque molestie porta magna at",
  },
  {
    id: 17,
    firstName: "Ida",
    lastName: "Carson",
    email: "SMore@ipsum.ly",
    phone: "(158)777-7401",
    address: {
      streetAddress: "7412 Sollicitudin Ct",
      city: "Rogersville",
      state: "MT",
      zip: "90980",
    },
    description:
      "morbi consectetur amet etiam egestas amet lorem mattis ante magna sollicitudin elementum sed pulvinar magna odio id aliquam dolor sed vel etiam aliquam placerat scelerisque eget magna sollicitudin rutrum lectus orci et",
  },
  {
    id: 762,
    firstName: "Leroy",
    lastName: "Kornation",
    email: "TBruintjes@at.gov",
    phone: "(543)224-7594",
    address: {
      streetAddress: "4361 Curabitur Ct",
      city: "Castle Rock",
      state: "IL",
      zip: "19263",
    },
    description:
      "scelerisque consectetur amet dolor convallis sollicitudin vitae velit mattis egestas morbi donec curabitur vitae dolor suspendisse pulvinar velit sed malesuada sed vel facilisis elit mattis nec orci sed at hendrerit aliquam at",
  },
];
